### ISSUE TITLE
Compatibilidade com iOS 12.5

### ISSUE THREAD

**Issue by EuSouManuelReis** [stayawayinesctec/stayaway-app#105]
Olá,

A Apple lançou na segunda-feira uma actualização para o iOS 12 (12.5) com o objectivo de expandir as notificações de exposição a aparelhos incompatíveis com o iOS 13 (nomeadamente o iPhone 5s, iPhone 6 e iPhone 6 Plus).

Existem planos para actualizar a aplicação para ser compatível com esta versão?

**Comment by fmaia** [comment]
Olá, 
Não conseguimos prever ainda uma data de lançamento mas estamos a trabalhar para que a STAYAWAY COVID passe a ser compatível com o iOS 12.5.
