### ISSUE TITLE
No Exposure IDs recorded

### ISSUE THREAD

**Issue by elffuhs** [stayawayinesctec/stayaway-app#113]
App version: 1.1.3
Google play services: 21.21.16
OS: MIUI 12.5

After installing the APP and using it for a few days no exposure IDs are being recorded at all.
Tried to uninstall the app, and install it via settings, but when selecting Portugal, it says no app is recorded for use in portugal by my health authority.

**Comment by fmaia** [comment]
@elffuhs, thank you for opening the issue and reporting your problem. Could you please forward such question to the support line at stayaway@inesctec.pt ? Thank you!
