### ISSUE TITLE
Linking to play-services-nearby's HEAD

### ISSUE THREAD

**Issue by marado** [stayawayinesctec/stayaway-app#20]
Currently you're pointing to the "master's HEAD version" of `play-services-nearby-18.0.3-eap.aar`, but you don't have any certainty that the file won't change, or disappear (for eg., being replaced with an `18.0.4` version of the file).

You should instead point to the actual version of the file we are supposed to be using, ie:

https://github.com/google/exposure-notifications-android/raw/58f6dc872016e2a42d174178dcefcae5d7590952/app/libs/play-services-nearby-18.0.3-eap.aar

**Comment by marado** [comment]
Actually, I just now realized that the SDK itself bundles play-services-nearby: https://github.com/DP-3T/dp3t-sdk-android/tree/master/dp3t-sdk/sdk/libs , so, instead of getting an extra copy, since we depend on the SDK, can't we use the aar provided in it, for the same version of the SDK being used?

**Comment by djcouto** [comment]
This is a good point, and actually it just happened.

Since this is a small change I will fix it with PR #27.

Regarding your last comment, this file needs to be manually copy to the project and we can't access it through the dp3t dependency.
