### ISSUE TITLE
Lack of Changelog

### ISSUE THREAD

**Issue by abacao** [stayawayinesctec/stayaway-app#35]
Changelog is a nice thing to have in a project like this

**Comment by marado** [comment]
Indeed: not only a repository-visible changelog (eg., a CHANGELOG.md, or descriptions on the releases at https://github.com/stayawayinesctec/stayaway-app/releases), but an actual changelog screen showing to the app users what has changed would be useful.

**Comment by djcouto** [comment]
Hi @abacao.

We agree that having a changelog is important and we will start one on the next release.

Thank you

**Comment by abacao** [comment]
Hello,
This issue was closed 4 days ago and the last commit was done 19h ago.
This issue shouldn't be closed until the Changelog is implemented.
