### ISSUE TITLE
App contacts Google

### ISSUE THREAD

**Issue by gonmf** [stayawayinesctec/stayaway-app#38]
Dependency `react-native-netinfo` contacts a third-party (Google) by default.

Default configuration: https://github.com/react-native-community/react-native-netinfo/blob/master/src/internal/defaultConfiguration.ts

Used in https://github.com/stayawayinesctec/stayaway-app/blob/master/src/app/sagas/services/index.js

This issue was already raised in at least one other of the contact tracing apps: https://seancoates.com/blogs/how-i-helped-fix-canadas-covid-alert-app

**Comment by marado** [comment]
FWIW, Canada's fix was simple, just this:
https://github.com/cds-snc/covid-alert-app/commit/f24349a3c809c45286936124c7ea4d75a0b5651a

**Comment by djcouto** [comment]
Hi @gonmf and thank you for calling our attention to this issue.

Since we do not highly depend on this package, we decided to remove it.

I'll create a PR with this change and it will be rolled out in the next release.
