### ISSUE TITLE
Google play missing COVID-19 ENS 'badge'

### ISSUE THREAD

**Issue by filipebatista** [stayawayinesctec/stayaway-app#47]
Usually the apps that use the Exposure Notifications System have that classification in the Google Play store.![Corona-warn-app](https://user-images.githubusercontent.com/1062959/91663357-2f93a300-eae0-11ea-9a1f-751dff985976.png)

Maybe that information should added.

**Comment by djcouto** [comment]
Hi @filipebatista 👋 

STAYAWAY should have this badge too and we've already reported this to google.
When this is fixed we will close this issue.

Thank you for calling our attention to this 👍

**Comment by djcouto** [comment]
This is now solved. 
Closing this.
