### ISSUE TITLE
No updates since app instalation

### ISSUE THREAD

**Issue by ruisebastiao** [stayawayinesctec/stayaway-app#49]
![image](https://user-images.githubusercontent.com/5761011/91837366-0db33100-ec44-11ea-9608-8da0c595cb8c.png)

after installing the application, the date of the last update remained unchanged, is there any way to force an update?

**Comment by ruisebastiao** [comment]
disable and re-enable the trace option solves the problem

**Comment by maghuro** [comment]
I'm getting the exactly same problem, and I use your solution as my solution too - disable and re enable g
Trace option
Definitely a big issue to be solved.

**Comment by emanuelmarques** [comment]
Same here. Android also mentions that they're were no new scans. Is it even working?

![Screenshot_20200902_032926_com google android gms](https://user-images.githubusercontent.com/8319881/91925300-9e355400-eccc-11ea-8865-f83deb6028ce.jpg)

**Comment by emanuelmarques** [comment]
After re enabling the tracing option, it updates the date on the app, but android still mentions no new scan

**Comment by gerdemb** [comment]
I am having the same issue on iOS 13.6.1. The last updated is stuck for two days. Also, seems to be making multiple exposure checks at the same time. Not sure if this correct or not.

![image](https://user-images.githubusercontent.com/218609/91964593-3b14e300-ed07-11ea-9256-0ce3c9ac6e2d.png)

![image](https://user-images.githubusercontent.com/218609/91964644-4ec04980-ed07-11ea-8e6a-f37c506ce068.png)

**Comment by gerdemb** [comment]
> I am having the same issue on iOS 13.6.1. The last updated is stuck for two days.

After ~48 hours being stuck, the last updated date changed to the current date.

**Comment by PauloFreire70** [comment]
Acontece-me o mesmo, desde o iOS update que deixou de funcionar. Reinstalei e revi tudo e aparece-me "sem actualizações". Isto assim não serve para nada, deviam dar atenção máxima e corrigir corrigir o quanto antes. Assim a aplicação não serve para nada.

**Comment by fmaia** [comment]
Version 1.0.1 addresses issues with app state update.
After updating to 1.0.1 the user should wait at least 24h until the app is able to update its status. 
This is due to the fact that there is a limit to the number of exposures checks allowed by the OS.
Please, check if waiting this period of time resolves the issue after installing version 1.0.1.

**Comment by maghuro** [comment]
V1.0.1 didn't solve the problem.
I'm stuck at September 5th.
I've used the German covid app and it updated every 24h

**Comment by fmaia** [comment]
STAYAWAY COVID's version 1.0.1 was only made available yesterday. Users should wait 24h after the update until the app can successfully update the state due to restrictions with Exposure Notification API calls. Please, check if waiting this period of time solves the issue.

**Comment by PauloFreire70** [comment]
I confirm that now it's working again. I've updated the App yesterday and it did not changed anything until today. So now it shows properly. Why are we reporting in English when the App is used by Portuguese people anyway? 
Thanks 👍

**Comment by ruisebastiao** [comment]
Being a fan of FOSS ("Free and Open-source") software I was particularly happy when i heard that the source code was going to be made available on github. So the code could be used not only by Portuguese people but by anyone else in the world whether they are enthusiasts or even students. Seeing English as an international language, i think using it is a good option. IMO

**Comment by ruisebastiao** [comment]
Version 1.0.1 fixes this issue
