### ISSUE TITLE
Explain why you need all the different permissions/access

### ISSUE THREAD

**Issue by filipebatista** [stayawayinesctec/stayaway-app#51]
There are several people asking why the location access is needed when they already enabled the bluetooth. This leads to distrust and that people won't install the app. 

Maybe during the onboarding additional screens should be added to explain why all the permissions/access are needed.

**Comment by GoncaloGarcia** [comment]
According to the DPT3 [documentation](https://github.com/DP-3T/documents/blob/master/COVID19%20Response%20-%20What%20Data%20Is%20Necessary%20For%20Digital%20Proximity%20Tracing.pdf), only bluetooth should be needed.

**Comment by marado** [comment]
The explanation for the current state is here:
https://www.mobihealthnews.com/news/bluetooth-contact-tracing-apps-built-google-apples-apis-still-collect-android-users-location

On Android 11 that changes (but Stayaway hasn't adapted for that yet).

**Comment by Jpfonseca** [comment]
There's a new version of the exposure SDK by Google and Apple which should require only the use of Bluetooth.

More info by [Apple](https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_express)

Google seems to still be working on [it](https://github.com/google/exposure-notifications-verification-server/pull/437) from the quick search I did.

**Comment by filipebatista** [comment]
In the case of Android the location needs to be enable because of the bluetooth scanning
https://support.google.com/android/answer/9930236?hl=en

_**If the Exposure Notifications System does not use my location data, why do I need to turn on my phone's location setting to use it?**
The Exposure Notification technology uses Bluetooth scanning to understand what devices are near one another. On all phones running Android 6.0 and above, to use Bluetooth scanning, the device location setting needs to be turned on for all apps, not just apps built with the Exposure Notifications System._

My point here was to find a way to provide more information to the user about why this access is necessary

**Comment by pestrela** [comment]
This is a unfortunate legacy situation that may indeed induce confusion on users. 
Agreed to mention this on the onboarding process.

For interested user this is a good tecnical explanation of the sitution (see at 30m07s):
https://www.youtube.com/watch?v=qQg4IibkOK4

This is how I explain this to non-tecnical users myself:
https://pestrela.github.io/covid/#porque-e-que-o-gaen-no-android-necessita-de-localiza%C3%A7%C3%A3o

thanks for your work
