### ISSUE TITLE
iOS 13.7 issues - app seems not to check for exposures

### ISSUE THREAD

**Issue by atmcarmo** [stayawayinesctec/stayaway-app#53]
Hi,

Since installed iOS 13.7, which brings phase two of the COVID Exposure API, it seems that the app is no longer updating.

![IMG_0333A15F93AA-1](https://user-images.githubusercontent.com/6707010/92127756-89a2aa00-edf9-11ea-9371-ac508cdb71d6.jpeg)

I updated from iOS 13.6 to 13.7 on the 1st of September and today is the 3rd of September and the app seems to be stuck and no longer updating.

I'm not sure if this is some sort of visualization issue only, because when checking Settings -> Exposure Notifications - Exposure Checks I see records being written to the system.

![IMG_0783](https://user-images.githubusercontent.com/6707010/92128184-0e8dc380-edfa-11ea-8ef3-1d84d3c0399f.PNG)

I'm available for any information needed. Thank you

**Comment by marado** [comment]
This might be related with the issues fixed on the most recent iOS SDK version of DP-3T:
https://github.com/DP-3T/dp3t-sdk-ios/pull/203

**Comment by atmcarmo** [comment]
Thanks @marado. 

Adding to this I can confirm I have logs on my network of DNS name resolution requests to the server that matches the screenshot above. This means that the request is being made and iOS registers the expose check.

<img width="371" alt="Screen Shot 2020-09-03 at 4 53 20 PM" src="https://user-images.githubusercontent.com/6707010/92138352-2a976200-ee06-11ea-887d-6f91f3bc74a8.png">

**Comment by emanuelmarques** [comment]
Appears to be the same as https://github.com/stayawayinesctec/stayaway-app/issues/49

**Comment by fmaia** [comment]
After updating to 1.0.1 the user should wait at least 24h until the app is able to update its status. This is due to the fact that there is a limit to the number of exposures checks allowed by the OS for each 24h period.
Please, check if waiting this period of time resolves the issue.

**Comment by atmcarmo** [comment]
This is now fixed in iOS 13.7. Closing this issue. Thank you!
