### ISSUE TITLE
"Monitoring" toggle doesn't work when the app language is set to Portuguese

### ISSUE THREAD

**Issue by edualm** [stayawayinesctec/stayaway-app#56]
**OS**: iOS 13.7
**App Version**: 1.0.1

The toggle for "Monitoring", which can be accessed via the hamburger menu > Monitoring, does not work if the app is set to Portuguese.

Tapping the toggle does not result in any observable action, and it stays on.

Interestingly, if the app is running in English, that toggle updates as expected when tapped.

I do not know if this is a regression in 1.0.1, as I have not tested this in 1.0.

**Comment by fmaia** [comment]
Thank you for pointing out this issue. 
We've identified the problem and PR @#58 addresses this issue.
