### ISSUE TITLE
App doesn't force update when switching from background to foreground

### ISSUE THREAD

**Issue by edualm** [stayawayinesctec/stayaway-app#57]
**OS**: iOS 13.7
**App Version**: 1.0.1

After updating the app to 1.0.1, the "last checked date" is still at 1/Sept, even after restarting the app a few times and switching it from foreground to background.

I'd consider this "normal", as I don't expect it to always be updating, but the changelog of version 1.0.1 leads me to beleive it's not:

```
Add force app sync when app comes from background or foreground
```

**Comment by fmaia** [comment]
After updating to 1.0.1 the user should wait at least 24h until the app is able to update its status. This is due to the fact that there is a limit to the number of exposures checks allowed by the OS. 
Please, check if waiting this period of time resolves the issue.

**Comment by edualm** [comment]
That fixed the issue.
