### ISSUE TITLE
Where is the server source code?

### ISSUE THREAD

**Issue by rlafuente** [stayawayinesctec/stayaway-app#59]
Today, Inesc Tec's president reinforced the intent to fully open the platform's source code. However, the server-side source code seems to be missing.

There is a [stale fork of the DP3T server backend](https://github.com/stayawayinesctec/dp3t-sdk-backend), with no edits since July 14. This means that two scenarios are possible:

- Either this fork is being used as the server backend, meaning that the framework is missing security updates from the last couple of months, and that no improvements have been made during the testing period 
- Or this fork is not the actual code of the server, meaning that the server code is not published.

Of course, the 2nd option seems much more likely, which is why it's important to know why the platform's source code is not yet fully published, contrary to public statements. Can anyone explain?

**Comment by rlafuente** [comment]
Correction: The statement was that the source code is already fully published, which doesn't seem to be true.

**Comment by fmcruz** [comment]
Actually it is true. Please note that the repository of the backend being used in production is located here [https://github.com/stayawayinesctec/dp3t-docker](url)
While the repository you mention serves a PR still in review in DP3T [https://github.com/DP-3T/dp3t-sdk-backend/pull/185](url)

**Comment by rlafuente** [comment]
Thank you for your prompt response, @fmcruz. I stand corrected, though it'd be helpful to have a note in the docs stating what is what.
