### ISSUE TITLE
New version of play-services-nearby

### ISSUE THREAD

**Issue by filipebatista** [stayawayinesctec/stayaway-app#62]
There seems to be a new version of the `play-services-nearby`-  `play-services-nearby-exposurenotification-1.6.1-eap.aar` in  https://github.com/google/exposure-notifications-android/tree/master/app/libs.

The Corona-Warn-App for Germany seems to be already using it (https://github.com/corona-warn-app/cwa-app-android/pull/1057) and according to the comments in the PR it seems that this new version solves the problem of Location setting need in order to work (for devices which support locationless scanning)
> fixed Location-Settings on Android 11 Devices with EN 1.6.1 (Location not needed anymore)

**Comment by djcouto** [comment]
The new version of the `play-services-nearby` binary was updated on #100.

Closing this.
