### ISSUE TITLE
Last updated date doesn't update on Version 1.0.1 on iOS 13.7

### ISSUE THREAD

**Issue by gerdemb** [stayawayinesctec/stayaway-app#65]
Phone is running iOS 13.7. Version 1.0.1 of APP installed on Sep 7, 2020. "Last updated" date displayed by the APP is "9.10.2020". Today is Sep 13, 2020. APP is opened at least once a day. Exposure checks are being logged by iOS.

Happy to provide more information if requested.

![IMG_C2805E55C723-1](https://user-images.githubusercontent.com/218609/93013930-8a2f0380-f5a4-11ea-80f5-875fcc4d6711.jpeg)
![IMG_B71BD590BDC4-1](https://user-images.githubusercontent.com/218609/93013969-d37f5300-f5a4-11ea-8a37-c4163028b83a.jpeg)
![82A28229-5F9A-4ECA-9F96-C0A105ADA267](https://user-images.githubusercontent.com/218609/93013972-d67a4380-f5a4-11ea-90e8-b09d48a1817d.PNG)
![DB6F5711-EA8D-4083-9D87-FDF6D9902311](https://user-images.githubusercontent.com/218609/93013973-d9753400-f5a4-11ea-89b0-892f01f88a51.PNG)

**Comment by fmaia** [comment]
A new version of the app is being released today (v1.0.2). 
Could you please check if this version solves this problem? Thank you!

**Comment by gerdemb** [comment]
> A new version of the app is being released today (v1.0.2).
> Could you please check if this version solves this problem? Thank you!

On September 14 (4 days later) the date started to update again. 

I updated to v1.0.2 today and will report again if the problem reoccurs.

**Comment by fmaia** [comment]
Thank you. I'm closing this issue. If the problem resurfaces we will revisit it.
