### ISSUE TITLE
App not updating

### ISSUE THREAD

**Issue by luismeruje** [stayawayinesctec/stayaway-app#67]
Hello, sorry for not reporting this problem earlier since I was part of the pilot program, but didn't get around to give feedback.

Similar to #65 my app isn't updating. The only times my app updated, indicated by the field "atualizado a:", was once when I installed the app, and once after the app reset around the time the full release was launched.
Right now it says updated on 31st of August and today is the 16th of September.

App version: 1.0.1
Phone: Pocophone f1 (Xiaomi)
MIUI version (modified android from xiaomi): MIUI Global 11.0.9
Android version: 10QKQ1.190828.002

I know one other person who told me he had the same problem.

**Comment by fmaia** [comment]
Thank you for the feedback. Is this still the case with version 1.0.2?
It is worth noting that devices such as Xiaomi and Huawei have custom battery management components that may prevent the app from running in the background. This will block the app from updating regularly. Please check if version 1.0.2 mitigates this issue.

**Comment by luismeruje** [comment]
@fmaia version 1.0.2 isn't available for me on the play store, unless you mean to compile it from source?

**Comment by fmaia** [comment]
@luismeruje version 1.0.2 was already published for all Android users. Sometimes it takes time for it to appear in all Play Store searches however, in this case, it should already appear since more than 24h have passed since we released it globally. Could you please check again? Thank you!

**Comment by luismeruje** [comment]
@fmaia Just checked, reinstalled the app but it's still v1.0.1. However, I set the app battery settings to "no restrictions" which seems to have solved the problem. Will check if it keeps updating over the next few days and if I get the update for v1.0.2.

Is there no way to automatically set the battery optimization settings to "no restrictions"? Probably most people who have this problem won't notice it, much less go around messing with the battery settings. And if the app doesn't update, then people won't know if they've been in contact with someone who is infected...

**Comment by fmaia** [comment]
@luismeruje thank you for the update. The problem with battery settings is that not all Android devices implement the same mechanisms. The app tries to point the user to the most common battery settings when you click the warning banner but this approach, unfortunately does not work in all devices. In particular, Xiaomi and Huawei tend to implement custom battery management components that users need to configure themselves.  
I'm closing the issue. It can be reopened if the problem resurfaces.
