### ISSUE TITLE
App does not contain a "select language" feature

### ISSUE THREAD

**Issue by jpac-run** [stayawayinesctec/stayaway-app#79]
There is no way of selecting the language of the app (at least that I'm aware of). I'm assuming that it uses the system's language but it should have a way to set the language, either when the user opens the app for the first time or in a settings page.

**Comment by antoniogoulao** [comment]
@jpac-run in the menu button in the top right corner you can select between English and Portuguese

**Comment by jpac-run** [comment]
![Screenshot_20201015-172552](https://user-images.githubusercontent.com/30054840/96158788-c7701380-0f0b-11eb-8c76-2fefbbf36aa2.jpg)

Android version: 9
Device: OnePlus 3
OS: OxygenOS 9.0.6

**Comment by jaxxibae** [comment]
![image](https://user-images.githubusercontent.com/32089154/96169385-ec6b8300-0f19-11eb-8f67-d1b1352d7fc4.png)
Well that's odd, CNR.

Android 10 QKQ1.190828.002
Xiaomi Mi 9 Lite
MIUI 12.0.3 Global

(maybe it's because of the language settings of your device?)

**Comment by djcouto** [comment]
Hi,

Language selection was introduced in 1.0.3 as you can see in the [release notes](https://github.com/stayawayinesctec/stayaway-app/releases/tag/v1.0.3).

You probably need to update your app.
