### ISSUE TITLE
Security. Vulnerabilities in your dependencies tree and build process

### ISSUE THREAD

**Issue by bertolo1988** [stayawayinesctec/stayaway-app#84]
By including dependencies with caret: (example:"react-native-version-number": "^0.3.6") you are allowing the mantainer of the dependency to include any code he wishes in your app just by releasing a minor without giving you a chance to review his changes.

Notice this can also be done through sub dependencies or through your build process (example: devDependencies could inject malicious code in your source on npm install or during build).

Example: https://www.veracode.com/blog/research/discovering-malicious-packages-published-npm

**Comment by djcouto** [comment]
Hi,

Thank you for calling our attention to this issue.

We were aware of this and have already resolved it for the `react-native-version-number` dependency on this [commit](https://github.com/stayawayinesctec/stayaway-app/commit/054a9c84b8f8ed0a753424b51a6fb137d8f9ef31).

Thank you for your contribution.

**Comment by bertolo1988** [comment]
Can we reopen this?

https://thehackernews.com/2021/02/dependency-confusion-supply-chain.html
